const express = require("express")
const app = express()

const productRoute = require("./router/productRoute")
const authRoute = require("./router/authRoute")
const userRoute = require("./router/userRoute")
const cartRoute = require("./router/cartRoute")
const orderRoute = require("./router/orderRoute")
const adminRoute = require("./router/adminRoute")
const settingsRoute = require("./router/settingsRoute")
const roleRoute = require("./router/roleRoute")

app.use("/api/products", productRoute)
app.use("/api/auth", authRoute)
app.use("/api/user", userRoute)
app.use("/api/cart", cartRoute)
app.use("/api/orders", orderRoute)
app.use("/api/admin", adminRoute)
app.use("/api/settings", settingsRoute)
app.use("/api/roles", roleRoute)
